/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.lingfor;

public class App {

    public static void main(String[] args) {

        // String filePath = "filePath";
        // byte[] data = new byte[] {};

        // //Behavior
        // FileServiceImpl fileService = new FileServiceImpl();
        // UploaderBehavior uploaderBehavior = new UploaderBehavior(fileService);
        // uploaderBehavior.upload(filePath, data);


        // //State
        // File file = new File();
        // file.init(filePath, data);
        // UploaderState uploaderState = new UploaderState(file);
        // uploaderState.upload();
        
    }
}
